trigger:
- master

# pr: none

pool:
  name: 'Azure Pipelines'

steps:
- task: Npm@1
  inputs:
    command: 'install'

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - task: Npm@1
    inputs:
      command: publish
      publishEndpoint: npmjs.com